server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: back
          uri: lb://MICSERVICE-BACK
          predicates:
            - Path=/back/**
          filters:
            - StripPrefix=1
        - id: front
          uri: lb://MICSERVICE-FRONT
          predicates:
            - Path=/**

